import type { ModuleProps, ModuleId } from "../types";
import { SectionLabel } from "../shared";

interface Report {
  title: string;
  type: string;
  updated: string;
  from: ModuleId;
  color: string;
}

const reports: Report[] = [
  { title: "AI in Healthcare — Editorial Brief", type: "Editorial intelligence", updated: "Today", from: "research", color: "#0ea5e9" },
  { title: "MSc AI — Competitive Benchmark", type: "Programme analysis", updated: "Today", from: "programmes", color: "#7c3aed" },
  { title: "Climate Change — Expertise Map", type: "Institutional search", updated: "Yesterday", from: "research", color: "#059669" },
  { title: "Q2 Research Growth — Executive Insights", type: "Strategic insights", updated: "2 days ago", from: "insights", color: "#2563eb" },
  { title: "Repository Intake — 100 papers classified", type: "Repository automation", updated: "2 days ago", from: "repository", color: "#d97706" },
];

export default function ReportsModule({ goTo }: ModuleProps) {
  return (
    <div className="mx-auto max-w-[820px]">
      <h2 className="font-display text-[24px] font-medium text-[#0f172a]">Reports</h2>
      <p className="mt-1 text-[14px] text-[#64748b]">
        Every Operon output is saved as a living, source-grounded report you can revisit, share, or push into workflow.
      </p>

      <div className="mt-6">
        <SectionLabel>Generated by Operon</SectionLabel>
        <div className="space-y-2.5">
          {reports.map((r) => (
            <button
              key={r.title}
              onClick={() => goTo(r.from)}
              className="flex w-full items-center gap-4 rounded-xl border border-[#e6e9ef] bg-white p-4 text-left transition-all hover:shadow-md"
            >
              <span
                className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg"
                style={{ backgroundColor: `${r.color}14`, color: r.color }}
              >
                <svg className="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M7 3h7l5 5v13H7z" />
                  <path d="M14 3v5h5M10 13h6M10 17h5" />
                </svg>
              </span>
              <span className="min-w-0 flex-1">
                <span className="block font-display text-[15px] font-medium text-[#0f172a]">{r.title}</span>
                <span className="text-[12.5px] text-[#94a3b8]">{r.type}</span>
              </span>
              <span className="shrink-0 text-[12px] text-[#94a3b8]">{r.updated}</span>
              <span className="shrink-0 text-accent">→</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}
